### PR TITLE
Update and resolve for wsl also linux distro

### PR DESCRIPTION
**Pull request by asifulmamun**
It was simple bug DB info and in .env.example file and local IP, also PHP docker file added nodejs, npm. Also added documentation for easy installation

### CODE REVIEW

**Comment by sam-ngu** [comment]
Hey, thanks for the PR! 
Is there a reason to add nodejs and npm?
Also ideally the env.example should not be containing anything else other than the vars related to the docker container

**Review by sam-ngu — COMMENTED** [review]
Is there a reason to add nodejs and npm?
Also ideally the env.example should not contain anything else other than the vars related to the docker container
The docs although are useful for beginners, but are irrelevant to this repo unfortunately, please remove them

**Comment by asifulmamun** [comment]
> Is there a reason to add nodejs and npm? Also ideally the env.example should not contain anything else other than the vars related to the docker container The docs although are useful for beginners, but are irrelevant to this repo unfortunately, please remove them

Yes, because after running the docker when need to install with node packages for laravel, npm i

**Comment by sam-ngu** [comment]
sorry, not every project wants node and npm in the server container.
If you want to install npm packages, you could spin up another node docker container or install them on your host machine.

**Comment by andersonparada** [comment]
hi, did you configure anything additional to get "npm run dev" from vite to work?

sorry for my English.

**Comment by sam-ngu** [comment]
Closing this PR as I don't see a need to include node in the PHP fpm container, it will be better to add an additional container just for node.

**Comment by asifulmamun** [comment]
> hi, did you configure anything additional to get "npm run dev" from vite to work?
> 
> sorry for my English.

I install it manually, it's not required by @sam-ngu, so you can install it manually as per your requirements

**Pull request closed without merging**
